"""Pydantic models shared by the API and the processor."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, validator


class AuthEvent(BaseModel):
    user: str = Field(..., min_length=1, description="Unique user identifier")
    activity: str = Field(..., min_length=1, description="Auth activity name e.g. login, validate, reservas")
    status: str = Field(..., min_length=1, description="Outcome of the activity e.g. success, failed")
    detail: Optional[Any] = Field(
        None,
        description="Free-form detail or structured payload (string/dict)",
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Auxiliary information such as ip, device_id, geo",
    )
    auth_token: Optional[str] = Field(
        default=None,
        description="JWT, session id or token involved in the event",
    )
    auth_id: Optional[str] = Field(
        default=None,
        description="Unique authentication attempt identifier if available",
    )
    simulation_uuid: Optional[str] = Field(
        default=None,
        description="UUID identifying the simulation this event belongs to",
    )
    occurred_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp generated by the producer",
    )

    @validator("status", pre=True)
    def _normalize_status(cls, value: str) -> str:  # noqa: D417
        return value.upper()

    @validator("activity", pre=True)
    def _normalize_activity(cls, value: str) -> str:  # noqa: D417
        return value.lower()


class AnomalyDecision(BaseModel):
    user: str
    activity: str
    rule: str
    severity: str
    reason: str
    occurred_at: datetime
    detected_at: datetime
    latency_ms: int
    simulation_uuid: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    recent_events: List[Dict[str, Any]] = Field(default_factory=list)


class ProcessedEvent(BaseModel):
    user: str
    activity: str
    status: str
    received_at: datetime
    processed_at: datetime
    processing_time_ms: int
    anomalies: List[AnomalyDecision]
    notifications: List["NotificationResult"] = Field(default_factory=list)


class NotificationResult(BaseModel):
    user: str
    activity: str
    rule: str
    detected_at: datetime
    success: bool
    detail: Optional[str] = None


__all__ = ["AuthEvent", "AnomalyDecision", "ProcessedEvent", "NotificationResult"]
